cdn_provider: ''
favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: 'http://dev.drupal8a.com/modules/contrib/bootstrap/favicon.ico'
  use_default: true
features:
  comment_user_picture: true
  comment_user_verification: true
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
schema: 8000
