<?php

/**
 * @file
 * Contains custom_twig_extension.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function custom_twig_extension_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_twig_extension module.
    case 'help.page.custom_twig_extension':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Twig Demo') . '</p>';
      return $output;

    default:
  }
}
