<?php

/**
 * @file
 * Contains twig_demo.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function twig_demo_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the custom_twig_extension module.
    case 'help.page.twig_demo':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Twig Demo') . '</p>';
      return $output;

    default:
  }
}
